<?php
namespace App\Reporting\Format;
use App\Reporting\Report;

class HtmlSpecialFormatter extends HtmlFormater {
    public function FormaToHtml(Report $report)
    {
        $html = parent::FormaToHtml($report); // TODO: Change the autogenerated stub
        return '
            <div style="font-weight: bold"> 
        ' . $html . '
        </div>
        ';
    }
}